### PR TITLE
Switching tag name to RC

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
The package on the build server is showing up as `1.0.0` w/o the RC suffix.
Are we doing the right thing and that's expected until the PR is merged into `master` or an RC should be done in a different way? /cc @bording

**Comment by bording** [comment]
This is not correct. You should never change `master` to produce RCs. You are supposed to create them from a release branch.

**Comment by SeanFeldman** [comment]
Thank you @bording. That's the reason we pinged you on this PR, to verify that what we're doing is good or not. I'll close this PR to release RC using the proper way.

@indualagarsamy @timbussmann here's what Brandon mentioned: https://github.com/Particular/PlatformDevelopment/tree/master/branching-strategy#releasing-a-release-candidate-or-rtm

**Comment by SeanFeldman** [comment]
image

**Comment by bording** [comment]
@SeanFeldman The document you linked to does have the correct strategy to follow. The `release-candidate` branch you have here should not exist.

**Comment by SeanFeldman** [comment]
@bording we're in the process of deleting that branch. See  https://github.com/Particular/NServiceBus.Extensions.Hosting/pull/18#issuecomment-552248282.

I'm not a GitHub admin and need an admin to delete it. Asked Indu to do it.

**Pull request closed without merging**
